## loading pkg
library(rgbif)
library(Taxonstand)
library(CoordinateCleaner)
library(maps)

species <- "Myrsine coriacea"
occs <- occ_search(scientificName = species,
                   limit = 100000)
names(occs)
myrsine.data <- occs$data

dir.create("../data/raw/", recursive = TRUE)
write.csv(myrsine.data, 
          "data/raw/myrsine_data.csv", 
          row.names = FALSE)

head(myrsine.data)

# Let’s check the unique entries for the species name we just searched.
sort(unique(myrsine.data$scientificName))

# In this particular case, we have a species with a long history of synonyms. In the gbif data, there is already a column showing the currently accepted taxonomy:

table(myrsine.data$taxonomicStatus)

# We can also check which of the names are accepted or not:

table(myrsine.data$scientificName, myrsine.data$taxonomicStatus)

# Let’s use the function TPL() from package taxonstand to check if the taxonomic updates in the gbif data are correct. This function receives a vector containing a list of species 
# and performs both orthographical and nomenclature checking. 

species.names <- unique(myrsine.data$scientificName) 
dim(species.names)

tax.check <- TPL(species.names)

# Note that the function adds several new variables to the input data and creates columns such as New.Genus and New.Species 
# with the accepted name. We should adopt these names if 
# the column New.Taxonomic.status is filled with “Accepted”

# creating new object w/ original and new names after TPL
new.tax <- data.frame(scientificName = species.names, 
                      genus.new.TPL = tax.check$New.Genus, 
                      species.new.TPL = tax.check$New.Species,
                      status.TPL = tax.check$Taxonomic.status,
                      scientificName.new.TPL = paste(tax.check$New.Genus,
                                                     tax.check$New.Species)) 
# now we are merging raw data and checked data
myrsine.new.tax <- merge(myrsine.data, new.tax, by = "scientificName")

# To guarantee the documentation of all steps, we will export the data after the taxonomy check.

dir.create("data/processed/", recursive = TRUE)
write.csv(myrsine.new.tax, 
          "data/processed/data_taxonomy_check.csv", 
          row.names = FALSE)

plot(decimalLatitude ~ decimalLongitude, data = myrsine.data, asp = 1)
map(add = TRUE)

# Now we will use the the function clean_coordinates() from the CoordinateCleaner package to clean the species records. This function checks for common errors in coordinates such as institutional coordinates, sea coordinates, outliers, zeros, centroids, etc. This function does not accept not 
# available information (here addressed as “NA”) 
# so we will first select only data that have a 
# numerical value for both latitude and longitude.

myrsine.coord <- myrsine.data[!is.na(myrsine.data$decimalLatitude) 
                              & !is.na(myrsine.data$decimalLongitude),]

# Now that we don’t have NA in latitude or longitude, 
# we can perform the coordinate cleaning. This new 
# dataset has 2580 occurrences.

# output w/ only potential correct coordinates
geo.clean <- clean_coordinates(x = myrsine.coord, 
                               lon = "decimalLongitude",
                               lat = "decimalLatitude",
                               species = "species", 
                               value = "clean")

# Let’s plot the output of the clean data.

par(mfrow = c(1, 2))
plot(decimalLatitude ~ decimalLongitude, data = myrsine.data, asp = 1)
map(add = TRUE)
plot(decimalLatitude ~ decimalLongitude, data = geo.clean, asp = 1)
map(add = TRUE)

# When setting value = clean it returns only the potentially correct coordinates. For checking and reproducibility we want to save all the
# output with the flags generated by the routine. 
# Let’s try a different output.

myrsine.new.geo <- clean_coordinates(x = myrsine.coord, 
                                     lon = "decimalLongitude",
                                     lat = "decimalLatitude",
                                     species = "species", 
                                     value = "spatialvalid")



# merging w/ original data
myrsine.new.geo2 <- merge(myrsine.data, myrsine.new.geo, 
                          all.x = TRUE, 
                          by = "key") 

plot(decimalLatitude ~ decimalLongitude, data = myrsine.new.geo, asp = 1)
map(, , , add = TRUE)

write.csv(myrsine.new.geo2, 
          "data/processed/myrsine_coordinate_check.csv", 
          row.names = FALSE)

# covert this to a sf object. 
# Create an sf object from this coordinates. 
# Having sf, plotting the points.
# Explore the "tmap_mode" --> allows you to create plots or interacting maps. 

